language: python

python:
  - 3.5

install:
  - pip install git+git://github.com/keboola/python-docker-application.git

env:
  - KBC_DATADIR=$TRAVIS_BUILD_DIR/test/data/

script:
  - cd $KBC_DATADIR
  - py.test ./../../